import { useState } from "react";
import type { Lead } from "@/types/lead";
import { CloseIcon } from "@/components/ui/icons";
import { ConfirmDialog } from "@/components/ui/confirm-dialog";

export function DeletedLeadsDialog({ open, leads, busy, onClose, onRestore, onPermanentDelete }: { open: boolean; leads: Lead[]; busy?: string; onClose: () => void; onRestore: (id: string) => Promise<unknown>; onPermanentDelete: (id: string) => Promise<unknown> }) {
  const [permanent, setPermanent] = useState<Lead>(); if (!open) return null;
  return <><div className="modal-backdrop"><section className="modal deleted-modal"><header><div><p className="eyebrow">LIXEIRA</p><h2>Leads excluídos</h2></div><button className="icon-button" onClick={onClose}><CloseIcon /></button></header><div className="deleted-list">{leads.length ? leads.map((lead) => <article key={lead.id}><div><strong>{lead.name}</strong><span>{[lead.businessName, lead.city].filter(Boolean).join(" · ")}</span><small>Excluído em {lead.deletedAt ? new Date(lead.deletedAt).toLocaleString("pt-BR") : "—"}</small></div><button disabled={busy === `restore:${lead.id}`} onClick={() => void onRestore(lead.id).catch(() => undefined)}>Restaurar</button><button className="text-danger" onClick={() => setPermanent(lead)}>Excluir permanentemente</button></article>) : <div className="empty-queue"><h3>Nenhum lead excluído</h3></div>}</div></section></div><ConfirmDialog open={Boolean(permanent)} title="Excluir permanentemente?" message={`O lead ${permanent?.name ?? ""} e todo o histórico serão apagados definitivamente. Esta ação não pode ser desfeita.`} confirmLabel="Excluir definitivamente" danger busy={busy === `permanent:${permanent?.id}`} onClose={() => setPermanent(undefined)} onConfirm={() => permanent ? onPermanentDelete(permanent.id) : undefined} /></>;
}
